#!/bin/bash

set +e

bundle install --binstubs --path vendor/bundle "$@"

echo "==> Copying example .env file..."
cp -n .env.example .env

echo "==> Migrating database..."
rake db:create
rake db:migrate

echo "==> coderdojo-webapp is almost ready to go! Please continue the instructions in the README."